<#
.SYNOPSIS
    HunterOs Harness installer for Windows (PowerShell 5.1+).

.DESCRIPTION
    Creates a dedicated virtualenv at ~\.hunteros\venv and installs the
    harness into it:
      1. If this script lives inside a checkout (pyproject.toml next to it),
         installs that checkout editable: pip install -e <checkout>.
      2. Otherwise tries PyPI: pip install hunteros-harness.
      3. Otherwise falls back to pip install git+<RepoUrl>.

    Then it registers `hunter` + `hunt` shims in %USERPROFILE%\.hunteros\bin,
    adds that directory to your PowerShell profile's PATH (a tagged,
    idempotent block), and - on an interactive console - launches
    `hunter init` (the onboarding wizard).

    The script is idempotent: re-running it reuses the existing venv,
    refreshes the installation, rewrites the shims, and never duplicates the
    PATH block. A re-run is an update, never a re-prompt.

    Works under `irm <url> | iex` (no reliance on $PSScriptRoot). Set
    HUNTEROS_PROFILE to redirect the profile PATH write (CI, unusual setups).

.PARAMETER RepoUrl
    Git URL to install from when no local checkout and no PyPI release exist.
    Defaults to $env:INSTALL_REPO_URL when set, else the canonical repo.

.PARAMETER SkipSetup
    Do not run the onboarding wizard after installing.

.PARAMETER DryRun
    Write shims + PATH registration only (no python/pip/network).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File install.ps1
.EXAMPLE
    powershell -ExecutionPolicy Bypass -File install.ps1 -SkipSetup -DryRun
.EXAMPLE
    irm https://raw.githubusercontent.com/zaaaxx11/HunterOsHarness/main/install.ps1 | iex
#>
param(
    [string]$RepoUrl = $(if ($env:INSTALL_REPO_URL) { $env:INSTALL_REPO_URL } else { "https://github.com/zaaaxx11/HunterOsHarness.git" }),
    [switch]$SkipSetup,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Write-Step([string]$Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Write-Ok([string]$Message) { Write-Host "    $Message" -ForegroundColor Green }
function Write-Fail([string]$Message) {
    Write-Host ""
    Write-Host "ERROR: $Message" -ForegroundColor Red
    exit 1
}

$binDir = Join-Path $env:USERPROFILE ".hunteros\bin"
$venvDir = Join-Path $env:USERPROFILE ".hunteros\venv"
$pathMarker = "hunteros PATH"

Write-Host ""
Write-Host @'
 _   _   _   _   _   _   _____   _____   ____
| | | | | | | | | \ | | |_   _| | ____| |  _ \   / _ \  / ____|
| |_| | | | | | |  \| |   | |   |  _|   | |_) | | | | | \___ \
|_| |_|  \___/  |_| \_|   |_|   |_____| |_| \_\  \___/  |____/
  HunterOs Harness - evidence or nothing
'@
if ($DryRun) { Write-Host "[dry-run] shims + PATH registration only - no install" }
Write-Host ""

function Write-Shims {
    # Written unconditionally on every run (overwrite = refresh), even in
    # dry-run and even when the venv does not exist yet: they only take
    # effect once the venv entry points exist.
    New-Item -ItemType Directory -Path $binDir -Force | Out-Null
    $hunterShim = @'
@echo off
rem HunterOs Harness shim (generated by install.ps1) - wraps the venv entry point.
"%USERPROFILE%\.hunteros\venv\Scripts\hunter.exe" %*
'@
    $huntShim = @'
@echo off
rem HunterOs Harness shim (generated by install.ps1) - wraps the venv entry point.
"%USERPROFILE%\.hunteros\venv\Scripts\hunt.exe" %*
'@
    Set-Content -Path (Join-Path $binDir "hunter.cmd") -Value $hunterShim -Encoding ASCII
    Set-Content -Path (Join-Path $binDir "hunt.cmd") -Value $huntShim -Encoding ASCII
}

function Register-Path {
    # HUNTEROS_PROFILE exists so CI/dry-runs (and users with unusual setups)
    # can redirect the write; it is documented in the script header comment.
    $profilePath = if ($env:HUNTEROS_PROFILE) { $env:HUNTEROS_PROFILE } else { $PROFILE }
    if (-not (Test-Path $profilePath)) {
        New-Item -ItemType File -Path $profilePath -Force | Out-Null
    }
    if (Select-String -LiteralPath $profilePath -SimpleMatch $pathMarker -Quiet) {
        Write-Ok "PATH already registered in $profilePath"
    } else {
        Add-Content -LiteralPath $profilePath -Value @'

# >>> hunteros PATH >>>
# Added by the HunterOs Harness installer (idempotent - do not edit between markers).
$env:PATH = "$env:USERPROFILE\.hunteros\bin;$env:PATH"
# <<< hunteros PATH <<<
'@
        Write-Ok "PATH registered in $profilePath - open a NEW shell to pick it up"
    }
}

function Write-FinalPrintout {
    Write-Host ""
    Write-Host "Installed. Next steps:" -ForegroundColor Magenta
    Write-Host ""
    Write-Host "  1. Open a NEW shell (PATH updated), then run:" -ForegroundColor White
    Write-Host "       hunter" -ForegroundColor Yellow
    Write-Host "     The onboarding wizard configures your brain in about a minute -" -ForegroundColor White
    Write-Host "     then 'hunter chat' talks to it. ('hunt' works anywhere 'hunter' does.)" -ForegroundColor White
    Write-Host "  2. Run a governed hunt on an authorized target:" -ForegroundColor White
    Write-Host "       hunter hunt <url> - one-command hunt on an authorized target." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Scan only systems you own or are explicitly authorized to test." -ForegroundColor DarkGray
}

if ($DryRun) {
    Write-Step "Dry run: writing shims + PATH registration (no python/pip/network)"
    Write-Shims
    Write-Ok "shims written to $binDir (hunter, hunt)"
    Register-Path
    Write-FinalPrintout
    exit 0
}

# --- 1. Locate a Python >= 3.10 --------------------------------------------

$pythonExe = $null
$pythonArgs = @()

function Test-PythonVersion([string]$Exe, [string[]]$ExeArgs) {
    & $Exe @ExeArgs -c "import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)" 2>$null
    return ($LASTEXITCODE -eq 0)
}

if (Get-Command py -ErrorAction SilentlyContinue) {
    if (Test-PythonVersion "py" @("-3")) {
        $pythonExe = "py"
        $pythonArgs = @("-3")
    }
}
if (-not $pythonExe -and (Get-Command python -ErrorAction SilentlyContinue)) {
    if (Test-PythonVersion "python" @()) {
        $pythonExe = "python"
        $pythonArgs = @()
    }
}
if (-not $pythonExe) {
    Write-Fail "Python 3.10+ not found. Install it from https://www.python.org/downloads/ (tick 'Add python.exe to PATH'), then re-run this script."
}

$pythonLabel = (& $pythonExe @pythonArgs --version 2>&1 | Out-String).Trim()
Write-Step "Found Python: $pythonLabel"

# --- 2. Create or reuse the venv --------------------------------------------

$venvPython = Join-Path $venvDir "Scripts\python.exe"

if (Test-Path $venvPython) {
    Write-Step "Reusing existing venv: $venvDir"
} else {
    Write-Step "Creating venv at $venvDir"
    & $pythonExe @pythonArgs -m venv "$venvDir"
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $venvPython)) {
        Write-Fail "Failed to create the venv. Delete $venvDir and re-run."
    }
}

Write-Step "Upgrading pip (quiet)"
& $venvPython -m pip install --upgrade pip --quiet --disable-pip-version-check
if ($LASTEXITCODE -ne 0) { Write-Fail "pip upgrade failed - check your network/proxy settings." }

# --- 3. Install the harness ---------------------------------------------------
# Under `irm | iex` both $PSScriptRoot and $MyInvocation.MyCommand.Path are
# empty -> $localCheckout is false -> PyPI -> git fallback (the remote case).

$scriptDir = if ($PSScriptRoot) {
    $PSScriptRoot
} elseif ($MyInvocation.MyCommand.Path) {
    Split-Path -Parent $MyInvocation.MyCommand.Path
} else {
    $null
}
$localCheckout = [bool]$scriptDir -and (Test-Path (Join-Path $scriptDir "pyproject.toml"))

if ($localCheckout) {
    Write-Step "Local checkout detected - installing editable from $scriptDir"
    & $venvPython -m pip install -e "$scriptDir" --disable-pip-version-check
    if ($LASTEXITCODE -ne 0) { Write-Fail "Editable install failed - see the pip output above." }
} else {
    Write-Step "Installing hunteros-harness from PyPI"
    & $venvPython -m pip install hunteros-harness --disable-pip-version-check
    if ($LASTEXITCODE -ne 0) {
        Write-Step "PyPI install failed - falling back to git ($RepoUrl)"
        & $venvPython -m pip install "git+$RepoUrl" --disable-pip-version-check
        if ($LASTEXITCODE -ne 0) {
            Write-Fail "All install sources failed. Check the RepoUrl and your network, then re-run."
        }
    }
}

& $venvPython -c "import hunter; print('hunteros-harness', hunter.__version__, 'installed')" | Write-Host
if ($LASTEXITCODE -ne 0) { Write-Fail "Installation verification failed: the 'hunter' package did not import cleanly." }

# --- 4. Verify the venv entry points (pins the `hunt` alias) --------------------

if (-not (Test-Path (Join-Path $venvDir "Scripts\hunter.exe"))) {
    Write-Fail "the 'hunter' entry point is missing - re-run the installer"
}
if (-not (Test-Path (Join-Path $venvDir "Scripts\hunt.exe"))) {
    Write-Fail "the 'hunt' entry point is missing - re-run the installer"
}

# --- 5. Shims + PATH ---------------------------------------------------------------

Write-Shims
Write-Ok "shims written to $binDir (hunter, hunt)"
Register-Path

# --- 6. Auto-run the onboarding wizard (a declined/failed wizard never fails
#        the install; a re-run with an existing config is an update) ----------------

if ($SkipSetup) {
    Write-Step "Skipping setup (-SkipSetup)"
} elseif ($env:HUNTEROS_CONFIG -or (Test-Path (Join-Path $env:USERPROFILE ".hunteros\config.yaml"))) {
    Write-Step "Config found - skipping the wizard (run 'hunter init' to reconfigure)"
} elseif (-not [Console]::IsInputRedirected) {
    Write-Step "Launching the onboarding wizard"
    & (Join-Path $venvDir "Scripts\hunter.exe") init
    # native exe: a declined/failed wizard must not fail the install ($LASTEXITCODE ignored)
} else {
    Write-Step "Non-interactive session - run 'hunter init' to configure your brain"
}

# --- 7. Next steps --------------------------------------------------------------------

Write-FinalPrintout
