#!/usr/bin/env bash
# HunterOs Harness installer for macOS / Linux.
#
# Creates a dedicated virtualenv at ~/.hunteros/venv and installs the harness:
#   1. If this script lives inside a checkout (pyproject.toml next to it),
#      installs that checkout editable:  pip install -e <checkout>
#   2. Otherwise tries PyPI:           pip install hunteros-harness
#   3. Otherwise falls back to:        pip install git+<REPO_URL>
#
# Then it registers `hunter` + `hunt` shims in ~/.hunteros/bin, adds that
# directory to your shell rc's PATH (a tagged, idempotent block), and - on an
# interactive terminal - launches `hunter init` (the onboarding wizard).
#
# Usage:
#   ./install.sh [--skip-setup] [--dry-run] [git-url]
#   --skip-setup  do not run the onboarding wizard after installing
#   --dry-run     write shims + PATH registration only (no python/pip/network)
#
# The repo URL can also be overridden with the INSTALL_REPO_URL env var.
#
# Idempotent: re-running reuses the venv, refreshes the installation,
# rewrites the shims, and never duplicates the PATH block. A re-run is an
# update, never a re-prompt (the wizard is skipped when a config exists).
set -euo pipefail

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
ok()   { printf '    \033[32m%s\033[0m\n' "$1"; }
fail() { printf '\n\033[31mERROR: %s\033[0m\n' "$1" >&2; exit 1; }

usage() {
    echo "Usage: ./install.sh [--skip-setup] [--dry-run] [git-url]"
    echo "  --skip-setup  do not run the onboarding wizard after installing"
    echo "  --dry-run     write shims + PATH registration only (no python/pip/network)"
}

SKIP_SETUP=0; DRY_RUN=0
REPO_URL="${INSTALL_REPO_URL:-https://github.com/zaaaxx11/HunterOsHarness.git}"
for arg in "$@"; do
  case "$arg" in
    --skip-setup) SKIP_SETUP=1 ;;
    --dry-run)    DRY_RUN=1 ;;
    -h|--help)    usage; exit 0 ;;
    *)            REPO_URL="$arg" ;;
  esac
done

VENV_DIR="$HOME/.hunteros/venv"
BIN_DIR="$HOME/.hunteros/bin"
PATH_TAG='hunteros PATH'

echo
cat <<'BANNER'
 _   _   _   _   _   _   _____   _____   ____
| | | | | | | | | \ | | |_   _| | ____| |  _ \   / _ \  / ____|
| |_| | | | | | |  \| |   | |   |  _|   | |_) | | | | | \___ \
|_| |_|  \___/  |_| \_|   |_|   |_____| |_| \_\  \___/  |____/
  HunterOs Harness - evidence or nothing

BANNER
if [ "$DRY_RUN" = "1" ]; then
    echo "[dry-run] shims + PATH registration only - no install"
fi
echo

# --- shims (hunter + hunt) ----------------------------------------------------
# Written unconditionally on every run (overwrite = refresh), even in dry-run
# and even when the venv does not exist yet: they only take effect once the
# venv entry points exist.

write_shims() {
    mkdir -p "$BIN_DIR"
    cat > "$BIN_DIR/hunter" <<'SHIM'
#!/usr/bin/env bash
# HunterOs Harness shim (generated by install.sh) - wraps the venv entry point.
exec "$HOME/.hunteros/venv/bin/hunter" "$@"
SHIM
    cat > "$BIN_DIR/hunt" <<'SHIM'
#!/usr/bin/env bash
# HunterOs Harness shim (generated by install.sh) - wraps the venv entry point.
exec "$HOME/.hunteros/venv/bin/hunt" "$@"
SHIM
    chmod 755 "$BIN_DIR/hunter" "$BIN_DIR/hunt"
}

# --- PATH registration (tagged block, deduped) -----------------------------------
# rc file: zsh -> ~/.zshrc, anything else -> ~/.bashrc. The block is appended
# at most once (grep -qF inside an if keeps set -e safe); the rc file is
# created mode 600 when missing.

register_path() {
    local rc
    case "$(basename "${SHELL:-}")" in
        zsh) rc="$HOME/.zshrc" ;;
        *)   rc="$HOME/.bashrc" ;;
    esac
    if [ ! -f "$rc" ]; then
        ( umask 077 && touch "$rc" )
    fi
    if grep -qF "$PATH_TAG" "$rc"; then
        ok "PATH already registered in $rc"
    else
        cat >> "$rc" <<'BLOCK'

# >>> hunteros PATH >>>
# Added by the HunterOs Harness installer (idempotent - do not edit between markers).
export PATH="$HOME/.hunteros/bin:$PATH"
# <<< hunteros PATH <<<

BLOCK
        ok "PATH registered in $rc - open a NEW shell or: source $rc"
    fi
}

final_printout() {
    echo
    printf '\033[35mInstalled. Next steps:\033[0m\n'
    echo
    echo "  1. Open a NEW shell (PATH updated), then run:"
    echo "       hunter"
    echo "     The onboarding wizard configures your brain in about a minute -"
    echo "     then \`hunter chat\` talks to it. (\`hunt\` works anywhere \`hunter\` does.)"
    echo "  2. Run a governed hunt on an authorized target:"
    echo "       hunter hunt <url> - one-command hunt on an authorized target."
    echo
    echo "Scan only systems you own or are explicitly authorized to test."
}

if [ "$DRY_RUN" = "1" ]; then
    step "Dry run: writing shims + PATH registration (no python/pip/network)"
    write_shims
    ok "shims written to $BIN_DIR (hunter, hunt)"
    register_path
    final_printout
    exit 0
fi

# --- 1. Locate a Python >= 3.10 ---------------------------------------------
PYTHON_EXE=""
PYTHON_LABEL=""

python_at_least_310() {
    "$1" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' >/dev/null 2>&1
}

for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1; then
        if python_at_least_310 "$candidate"; then
            PYTHON_EXE="$candidate"
            PYTHON_LABEL="$("$candidate" --version 2>&1 | head -n1)"
            break
        fi
        LAST_LABEL="$("$candidate" --version 2>&1 | head -n1)"
    fi
done

if [ -z "$PYTHON_EXE" ]; then
    if [ -n "${LAST_LABEL:-}" ]; then
        fail "Python 3.10+ required, found '$LAST_LABEL'. Install a newer Python (https://www.python.org/downloads/ or your package manager) and re-run."
    fi
    fail "Python 3.10+ not found. Install it (https://www.python.org/downloads/ or 'brew install python' / 'apt install python3') and re-run."
fi
step "Found Python: $PYTHON_LABEL"

# --- 2. Create or reuse the venv ----------------------------------------------
if [ -x "$VENV_DIR/bin/python" ]; then
    step "Reusing existing venv: $VENV_DIR"
else
    step "Creating venv at $VENV_DIR"
    "$PYTHON_EXE" -m venv "$VENV_DIR" || fail "Failed to create the venv at $VENV_DIR."
fi
VENV_PYTHON="$VENV_DIR/bin/python"
[ -x "$VENV_PYTHON" ] || fail "venv python missing at $VENV_PYTHON - delete $VENV_DIR and re-run."

step "Upgrading pip (quiet)"
"$VENV_PYTHON" -m pip install --upgrade pip --quiet --disable-pip-version-check \
    || fail "pip upgrade failed - check your network/proxy settings."

# --- 3. Install the harness ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"

if [ -f "$SCRIPT_DIR/pyproject.toml" ]; then
    step "Local checkout detected - installing editable from $SCRIPT_DIR"
    "$VENV_PYTHON" -m pip install -e "$SCRIPT_DIR" --disable-pip-version-check \
        || fail "Editable install failed - see the pip output above."
else
    step "Installing hunteros-harness from PyPI"
    if ! "$VENV_PYTHON" -m pip install hunteros-harness --disable-pip-version-check; then
        step "PyPI install failed - falling back to git ($REPO_URL)"
        "$VENV_PYTHON" -m pip install "git+$REPO_URL" --disable-pip-version-check \
            || fail "All install sources failed. Check the repo URL and your network, then re-run."
    fi
fi

"$VENV_PYTHON" -c "import hunter; print('hunteros-harness', hunter.__version__, 'installed')"

# --- 4. Verify the venv entry points (pins the `hunt` alias) ----------------------
[ -x "$VENV_DIR/bin/hunter" ] || fail "the 'hunter' entry point is missing - re-run the installer"
[ -x "$VENV_DIR/bin/hunt" ] || fail "the 'hunt' entry point is missing - re-run the installer"

# --- 5. Shims + PATH ----------------------------------------------------------------
write_shims
ok "shims written to $BIN_DIR (hunter, hunt)"
register_path

# --- 6. Auto-run the onboarding wizard (a declined/failed wizard never fails
#        the install; a re-run with an existing config is an update) ----------------
if [ "$SKIP_SETUP" = "1" ]; then
    step "Skipping setup (--skip-setup)"
elif [ -n "${HUNTEROS_CONFIG:-}" ] || [ -f "$HOME/.hunteros/config.yaml" ]; then
    step "Config found - skipping the wizard (run 'hunter init' to reconfigure)"
elif [ -t 0 ]; then
    step "Launching the onboarding wizard"
    "$VENV_DIR/bin/hunter" init || true
else
    step "Non-interactive session - run 'hunter init' to configure your brain"
fi

# --- 7. Next steps --------------------------------------------------------------------
final_printout
